import type { ContentItem, Topic } from './types';

interface Brief {
  id: string;
  title: string;
  url: string;
  publisher: string;
  topics: Topic[];
  concepts: string[];
  text: string;
  summary: string;
  minutes: number;
  kind?: ContentItem['kind'];
}

// Original editorial briefs, not harvested articles or precomputed model judgments.
// Each linked primary source was checked on 2026-09-26. See BURST-SOURCES.md.
const briefs: Brief[] = [
  {
    id: 'half-life', title: 'Predict when a learner will forget, then choose the next lesson',
    url: 'https://aclanthology.org/P16-1174/', publisher: 'Settles & Meeder', kind: 'paper',
    topics: ['language', 'ranking'], concepts: ['Spaced repetition', 'half-life regression', 'personalized review scheduling', 'recall probability'], minutes: 7,
    text: 'Half-life regression models how recall changes with time and learning history. Settles and Meeder apply this approach to language learning, making review timing a prediction problem rather than a universal calendar. A founder could use a learner’s review outcomes to decide which vocabulary deserves another encounter inside recommended content. Keep this memory estimate separate from whether the learner enjoyed an article. For an initial experiment, log the vocabulary item, elapsed time, attempted recall, and outcome, then compare a personalized schedule with a simple fixed review interval.',
    summary: 'Use recall history and elapsed time to personalize review timing. A content recommender can prioritize useful vocabulary encounters while keeping memory estimates separate from enjoyment signals.',
  },
  {
    id: 'cefr', title: 'A language level should describe what someone can actually do',
    url: 'https://www.coe.int/en/web/common-european-framework-reference-languages/level-descriptions', publisher: 'Council of Europe',
    topics: ['language', 'design'], concepts: ['CEFR can-do descriptors', 'skill-specific learner profiles', 'task difficulty'], minutes: 4,
    text: 'CEFR organizes language proficiency around communicative abilities across six broad levels. Its descriptors give a product team a more concrete vocabulary than a single beginner or advanced badge. For a language curation engine, a learner might understand an interview but struggle to summarize its argument aloud. The product implication is to store abilities by task and skill, then explain why an item offers an appropriate challenge. Treat an automatically inferred level as a hypothesis to validate through performance, rather than an authoritative assessment of the learner.',
    summary: 'Describe learner needs through observable communication tasks. Skill-specific profiles can explain content difficulty more meaningfully than one broad level, especially when predictions remain open to correction.',
  },
  {
    id: 'context-budget', title: 'Give the tutor the right memory, instead of every previous message',
    url: 'https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents', publisher: 'Anthropic', kind: 'article',
    topics: ['agents', 'language'], concepts: ['context selection', 'memory compaction', 'attention budget'], minutes: 6,
    text: 'Context engineering selects and maintains the information available to an agent during inference. Long histories can dilute relevant material instead of reliably improving a response. For a language tutor, the useful context might be the current speaking goal, recent recurring mistakes, and the source passage under discussion. Keep the original observations outside the prompt so a compact memory can be corrected later. A practical experiment compares complete conversation history with a small retrieved learner profile while measuring correction accuracy, response latency, and whether old misconceptions continue to appear.',
    summary: 'Select a compact learner profile for each tutoring task and preserve its underlying observations. Evaluate whether relevant context improves correction quality and speed compared with complete histories.',
  },
  {
    id: 'bounded-tutor', title: 'A reliable tutor starts with a small, observable workflow',
    url: 'https://www.anthropic.com/engineering/building-effective-agents', publisher: 'Anthropic', kind: 'article',
    topics: ['agents', 'language'], concepts: ['bounded agent workflow', 'tool contracts', 'evaluation gates'], minutes: 6,
    text: 'Workflows follow predefined paths, while agents can choose their own sequence of actions. Anthropic uses this distinction to guide system design and recommends beginning with simpler solutions. A language learning workflow could retrieve one passage, identify a teachable concept, ask a question, and evaluate the answer against a rubric. Each boundary gives the builder somewhere to inspect failures. Add autonomous searching only when the fixed workflow demonstrably misses a necessary capability. This makes the first tutor easier to evaluate and keeps a mistaken correction from triggering an uncontrolled chain of actions.',
    summary: 'Start a tutor with explicit retrieval, question, and evaluation stages. Inspect failures at those boundaries before adding autonomy, so capability grows from observed needs rather than complexity.',
  },
  {
    id: 'tutor-evals', title: 'Turn bad tutoring moments into a regression dataset',
    url: 'https://developers.openai.com/api/docs/guides/evals', publisher: 'OpenAI',
    topics: ['agents', 'language'], concepts: ['task-specific evaluation datasets', 'rubric-based grading', 'regression evaluation'], minutes: 5,
    text: 'An evaluation combines representative examples with criteria for judging model behavior. OpenAI’s evals guide describes defining a task, running model outputs against data, and examining results. For a language tutor, collect cases such as accepting an incorrect tense, overcorrecting a valid alternative, or giving away the answer. The editorial recommendation is to score these behaviors separately rather than hide them inside one satisfaction metric. Preserve the learner prompt and expected teaching behavior, then rerun the dataset whenever prompts, tools, or models change before exposing the revision to learners.',
    summary: 'Build an evaluation set from concrete teaching failures and score each behavior separately. Repeated evaluation makes prompt and model changes reviewable before they affect real learners.',
  },
  {
    id: 'typed-learning', title: 'Generate a lesson object your application can actually trust',
    url: 'https://ai-sdk.dev/docs/reference/ai-sdk-core/output', publisher: 'Vercel AI SDK',
    topics: ['agents', 'language', 'web'], concepts: ['structured output validation', 'lesson schema', 'evidence validation'], minutes: 4,
    text: 'Structured generation lets an application request data with an explicit shape. AI SDK distinguishes schema-validated objects from JSON output that only guarantees syntactic JSON validity. A lesson schema might contain a target phrase, a question, accepted answers, and a supporting source span. Schema validation catches missing fields or invalid types, but it does not prove that the teaching content is correct. A useful harness therefore checks the source span and applies a teaching rubric after parsing, while presenting failed validation as a recoverable error instead of silently publishing a lesson.',
    summary: 'Use a schema to turn generated lessons into dependable application data. Validate supporting evidence and teaching quality separately, because valid JSON and factual correctness are different properties.',
  },
  {
    id: 'learner-memory', title: 'Separate what happened in a lesson from what the learner knows',
    url: 'https://docs.langchain.com/oss/javascript/concepts/memory', publisher: 'LangChain',
    topics: ['agents', 'language', 'ranking'], concepts: ['semantic learner memory', 'episodic learning events', 'memory namespaces'], minutes: 5,
    text: 'Agent memory can retain facts, experiences, and procedures across different scopes. LangChain distinguishes conversation state from memories that persist across sessions and discusses both profile documents and collections of memories. For a language product, an incorrect answer is an event; a persistent difficulty with articles is an inference across events. Store these separately so a later success can revise the inference without erasing history. Namespaces can separate learners and goals, while a small retrieved memory supplies the tutor with relevant context for the current exercise.',
    summary: 'Keep lesson events separate from inferred learner knowledge. Persistent memories become easier to correct when their scope, supporting observations, and relevance to the current task remain explicit.',
  },
  {
    id: 'birdbrain', title: 'Personalize the challenge, not just the topic',
    url: 'https://blog.duolingo.com/learning-how-to-help-you-learn-introducing-birdbrain/', publisher: 'Duolingo', kind: 'article',
    topics: ['language', 'ranking'], concepts: ['learner-exercise difficulty', 'success probability', 'adaptive lesson selection'], minutes: 5,
    text: 'Duolingo describes Birdbrain as a model of learner knowledge and exercise difficulty. Its predictions help lesson selection consider whether an exercise offers the right challenge for a particular person. That suggests a useful distinction for a new curation product: interest in a topic and readiness for its language are separate questions. An interview about startups can be highly relevant yet too difficult to use without support. Prototype a difficulty control alongside topic relevance, then measure successful comprehension rather than assuming that more clicks mean a better learning experience.',
    summary: 'Rank content by both interest and learner-specific difficulty. Predicting a suitable challenge opens a more useful personalization loop than treating topic relevance as the entire learning objective.',
  },
  {
    id: 'fsrs', title: 'Review scheduling needs actual recall outcomes',
    url: 'https://github.com/open-spaced-repetition/fsrs4anki', publisher: 'Open Spaced Repetition',
    topics: ['language', 'ranking'], concepts: ['Spaced repetition', 'FSRS scheduling', 'review history', 'retention targets'], minutes: 7,
    text: 'FSRS is an open source approach to scheduling spaced repetition from review history. The repository provides implementations and resources for applying the scheduler to flashcard learning. A content engine can borrow the data discipline before integrating an algorithm: record what was tested, when it was reviewed, and how the learner rated recall. Reading a related article is not equivalent to passing that recall test. A practical product experiment would connect selected articles to a small review queue and examine whether learners retain useful vocabulary with an acceptable review burden.',
    summary: 'Collect review history before promising adaptive retention. Connecting articles to explicit recall checks can create a measurable learning loop without confusing content consumption with demonstrated vocabulary mastery.',
  },
  {
    id: 'speech-feedback', title: 'A transcript is evidence for a speaking tutor, not a pronunciation grade',
    url: 'https://arxiv.org/abs/2212.04356', publisher: 'Radford et al.', kind: 'paper',
    topics: ['language', 'agents'], concepts: ['weakly supervised speech recognition', 'transcription uncertainty', 'speaking feedback'], minutes: 8,
    text: 'Whisper studies speech recognition learned from large-scale weak supervision. Transcription can make spoken practice available to text-based analysis, but recognizing words is a different task from assessing pronunciation quality. A language tutor should retain the audio context and make uncertainty visible when a transcript looks implausible. As a product experiment, let a learner correct the transcript before an agent explains grammar or vocabulary choices. This prevents a recognition error from becoming an authoritative language correction and creates a clearer boundary between transcription, teaching, and assessment.',
    summary: 'Use transcription as an input to speaking feedback while keeping recognition and assessment separate. Letting learners correct uncertain transcripts can prevent false grammar lessons caused by recognition errors.',
  },
  {
    id: 'jev-at-scale', title: 'Use Jev for repeated decisions and an LLM for the explanation',
    url: 'https://vercel.com/i/what-is-jev', publisher: 'Vercel', kind: 'article',
    topics: ['ranking', 'agents'], concepts: ['System One decisions', 'decision-generation separation', 'batch candidate evaluation'], minutes: 4,
    text: 'Jev targets structured decisions rather than free-form text generation. Vercel introduces it as a System One model suited to repeated evaluation tasks such as classification and ranking. In a curation engine, an LLM can prepare a grounded content representation once, while a decision model evaluates that representation against changing user goals. The engineering implication is to measure these stages separately: preparation latency is different from decision throughput. Keep the question criteria consistent across candidates and show measured timings, rather than claiming that every stage of content ingestion runs at decision-model speed.',
    summary: 'Prepare grounded content once, then evaluate many candidates against a reader goal. Measure decision throughput separately from extraction and generation so the speed demonstration reflects the actual system.',
  },
  {
    id: 'jev-questions', title: 'The quality of a ranking starts with the question you ask',
    url: 'https://typesafe.ai/blog/introducing-system-one-models-and-jev', publisher: 'TypeSafe AI', kind: 'article',
    topics: ['ranking', 'agents'], concepts: ['atomic decision criteria', 'profile-conditioned forecasts', 'decision calibration'], minutes: 5,
    text: 'TypeSafe introduces System One models as a way to make fast decisions from supplied context. For a ranking product, this encourages explicit criteria instead of one vague request to score value. Ask whether a candidate supports the current goal, whether it adds unfamiliar concepts, and whether it suggests an implementable next step. The product still owns the policy that combines those judgments. Record the criteria and profile version with each result so a changed goal triggers fresh evaluation. A probability-like model output does not by itself establish calibration for a new user population.',
    summary: 'Translate value into explicit relevance, novelty, and actionability questions. Preserve criteria and profile versions with results, and evaluate calibration on observed outcomes before treating scores as dependable probabilities.',
  },
  {
    id: 'rlcd-data', title: 'Before training a decision model, define the event it must predict',
    url: 'https://www.together.ai/blog/how-to-train-your-own-jev', publisher: 'Together AI', kind: 'article',
    topics: ['rl', 'ranking'], concepts: ['RLCD training objective', 'verifiable decision outcomes', 'training-evaluation separation'], minutes: 9,
    text: 'Together’s Jev training walkthrough discusses Reinforcement Learning for Calibrated Decisions. The useful starting point for a founder is the relationship among an input, a decision question, and an outcome that can score that decision. For personalized curation, a useful rating collected after reading differs from a click collected before reading. Keep those labels separate and reserve evaluation examples before training. A small demonstration can teach the mechanics, but its training expense and results do not predict the cost or quality of a personalized production model on a different dataset.',
    summary: 'Define measurable decision outcomes and reserve evaluation data before training. Useful ratings, clicks, and mastery checks supply different supervision; a walkthrough does not establish production cost or quality.',
  },
  {
    id: 'bandit-feedback', title: 'A recommender only learns about the items it exposes',
    url: 'https://vowpalwabbit.org/docs/vowpal_wabbit/python/latest/tutorials/python_Contextual_bandits_and_Vowpal_Wabbit.html', publisher: 'Vowpal Wabbit',
    topics: ['ranking', 'rl'], concepts: ['contextual bandit exploration', 'logged action propensities', 'partial feedback'], minutes: 8,
    text: 'Contextual bandits choose an action from context and receive feedback about the chosen action. Vowpal Wabbit’s tutorial makes the explore-versus-exploit tradeoff concrete through a simulated recommendation problem. In a learning feed, showing only familiar favorites limits the evidence available about other topics. Record which candidates were eligible, which one appeared, and the selection probability when running a randomized policy. A prototype can start with explicit preference feedback, but future off-policy evaluation needs exposure information that cannot be reconstructed reliably from positive ratings alone.',
    summary: 'Log exposure and selection probabilities before testing exploratory recommendations. Feedback on displayed items is partial evidence, so positive ratings alone cannot support reliable evaluation of a different selection policy.',
  },
  {
    id: 'ranking-loss', title: 'Train for the order of a list, not only individual scores',
    url: 'https://www.tensorflow.org/ranking/overview', publisher: 'TensorFlow',
    topics: ['ranking', 'rl'], concepts: ['learning to rank', 'listwise objectives', 'ranking metrics'], minutes: 7,
    text: 'TensorFlow Ranking provides tools for training and evaluating learning-to-rank models. Ranking objectives focus attention on how candidates are ordered, which can differ from optimizing independent classification accuracy. For a personal reading queue, the first few positions matter more than a perfect ordering of documents nobody reaches. Define an evaluation set with graded usefulness judgments and compare the resulting top choices against a transparent baseline. Treat the choice of metric as a product decision: an ordering that predicts clicks well may still waste time or repeatedly surface concepts the reader already knows.',
    summary: 'Evaluate the order readers actually encounter, especially the first few positions. Choose ranking metrics around usefulness and time constraints rather than assuming independent accuracy or click prediction measures value.',
  },
  {
    id: 'side-features', title: 'Cold-start recommendations need more than an item ID',
    url: 'https://www.tensorflow.org/recommenders/examples/featurization', publisher: 'TensorFlow Recommenders',
    topics: ['ranking', 'agents'], concepts: ['recommendation side features', 'feature preprocessing', 'cold-start representations'], minutes: 6,
    text: 'TensorFlow Recommenders demonstrates preprocessing side features alongside identifier-based representations. Text and other attributes can supply information beyond a user or item ID. For a new language article, topic, concept coverage, difficulty, and format are available before anyone has interacted with it. These features offer a starting point for evaluation while feedback is sparse. Keep their provenance explicit: a publisher tag and an LLM-inferred difficulty are not equally reliable observations. Test each added feature against a simpler baseline to avoid building an elaborate profile that contributes little recommendation quality.',
    summary: 'Use content attributes to represent new items before interaction history exists. Track where each feature came from and test its contribution rather than assuming richer profiles always improve recommendations.',
  },
  {
    id: 'calibration', title: 'If a model says 80%, define what happens eight times in ten',
    url: 'https://arxiv.org/abs/1706.04599', publisher: 'Guo et al.', kind: 'paper',
    topics: ['ranking', 'rl'], concepts: ['probability calibration', 'reliability diagrams', 'temperature scaling'], minutes: 7,
    text: 'Calibration compares predicted confidence with how often the corresponding outcome occurs. Guo and colleagues study this mismatch in neural networks and examine calibration methods including temperature scaling. For content ranking, first define the event: perhaps a reader reports that an item helped a stated task. Then collect held-out outcomes and compare predictions with observations across probability ranges. A weighted feed score is a different quantity and should be labeled as such. Recheck calibration when the audience, question wording, or candidate distribution changes instead of treating it as a permanent property of a model.',
    summary: 'Define an observable event before evaluating forecast calibration. Use held-out outcomes and reliability comparisons, and keep a composite feed score distinct from a probability with an empirical interpretation.',
  },
  {
    id: 'dpo-pairs', title: 'Preference pairs need context to become useful training data',
    url: 'https://arxiv.org/abs/2305.18290', publisher: 'Rafailov et al.', kind: 'paper',
    topics: ['rl', 'ranking'], concepts: ['direct preference optimization', 'chosen-rejected pairs', 'preference context'], minutes: 8,
    text: 'Direct Preference Optimization derives an objective for learning from preferred and dispreferred responses. The paper offers an alternative to an explicit reward-model-and-RL training pipeline for language models. A curation product can learn a data-design lesson without immediately training anything: preserve both alternatives and the user goal when collecting a comparison. A preference for a short beginner explanation under one task need not imply a universal preference against technical depth. Build a held-out set and inspect inconsistent comparisons before deciding whether model training would improve on a profile-based ranking policy.',
    summary: 'Store both compared alternatives and the goal behind a preference. Context-rich pairs can support later training experiments, while held-out evaluation tests whether training improves on a simpler profile policy.',
  },
  {
    id: 'conformal', title: 'Prediction uncertainty deserves a contract of its own',
    url: 'https://arxiv.org/abs/1902.06579', publisher: 'Vovk et al.', kind: 'paper',
    topics: ['ranking', 'rl'], concepts: ['conformal calibration', 'predictive distributions', 'distribution assumptions'], minutes: 9,
    text: 'Conformal calibrators study methods for converting predictive distributions into calibrated prediction systems. This is a research direction about uncertainty, not a ready-made guarantee that a personal feed understands a learner. A practical reading goal is to identify which assumptions support a proposed uncertainty statement and whether the collected feedback meets them. In an evolving recommendation product, exposure policy and user preferences can change the data distribution. Before adopting a formal guarantee, document the target outcome, calibration data, and conditions under which the claim is intended to hold.',
    summary: 'Read uncertainty guarantees together with their assumptions and calibration data requirements. A changing recommendation policy can alter feedback distributions, so formal methods need a carefully defined product setting.',
  },
  {
    id: 'mmr', title: 'Five highly relevant articles can still repeat the same idea',
    url: 'https://www.cs.cmu.edu/~jgc/publication/The_Use_MMR_Diversity_Based_LTMIR_1998.pdf', publisher: 'Carbonell & Goldstein', kind: 'paper',
    topics: ['ranking', 'agents'], concepts: ['maximal marginal relevance', 'redundancy penalties', 'set-level utility'], minutes: 5,
    text: 'Maximal marginal relevance balances relevance with novelty relative to already selected material. The original work applies this idea to retrieval and summarization, where individually relevant documents can be redundant as a set. A founder building a daily learning brief can use the same design question: does the next article add anything beyond the items already chosen? Compare candidate similarity against the selected set and make the diversity tradeoff explicit. Evaluate the resulting reading bundle, rather than only judging each article in isolation, because a useful session needs complementary information.',
    summary: 'Select a complementary reading bundle by penalizing repetition among chosen items. Set-level usefulness can improve even when a slightly lower individual score contributes a genuinely different concept or perspective.',
  },
  {
    id: 'react-components', title: 'Compose a page from small React components',
    url: 'https://react.dev/learn/describing-the-ui', publisher: 'React',
    topics: ['web'], concepts: ['React component hierarchy', 'JSX markup', 'component composition'], minutes: 3,
    text: 'React components combine presentation and behavior into reusable pieces of an interface. The introductory documentation walks through describing a UI with components and JSX. A simple exercise is to split a static product page into a navigation bar, a product card, and a footer, then compose them in one parent. This is foundational material for someone beginning React. It introduces the vocabulary needed to read more advanced examples, but an experienced builder may only need the short reminder rather than another full tutorial on component structure.',
    summary: 'Practice the basic vocabulary of components and JSX by dividing a static page into reusable parts. Experienced React builders can likely compress this introduction into a brief reminder.',
  },
  {
    id: 'react-props', title: 'Pass data into a component with props',
    url: 'https://react.dev/learn/passing-props-to-a-component', publisher: 'React',
    topics: ['web'], concepts: ['React props', 'immutable inputs', 'component composition'], minutes: 3,
    text: 'Props let a parent supply information to a child React component. They can include values, objects, and other content, and the receiving component treats them as read-only inputs. A beginner exercise replaces a hardcoded avatar name and image with props, then renders several avatars from the same component. The main design lesson is to make each component’s required inputs visible in its interface. Once this pattern is familiar, rereading the full introduction offers limited novelty compared with studying a concrete state-management or rendering problem in an existing application.',
    summary: 'Turn hardcoded UI values into explicit component inputs and treat them as immutable. This foundational props tutorial is useful for beginners but may add little for experienced React developers.',
  },
  {
    id: 'react-conditions', title: 'Render an empty state with ordinary JavaScript conditions',
    url: 'https://react.dev/learn/conditional-rendering', publisher: 'React',
    topics: ['web'], concepts: ['conditional rendering', 'JSX expressions', 'empty-state branches'], minutes: 3,
    text: 'React uses JavaScript conditions to decide which JSX to render. The documentation introduces branches, conditional expressions, and logical operators for displaying different UI states. Build a small list that shows an empty message until it contains items, then add a separate loading branch. Keep the conditions readable as the number of states grows instead of nesting many expressions inside one line. This exercise teaches a basic rendering technique; it does not require a new state library or an elaborate application architecture to be useful.',
    summary: 'Use ordinary JavaScript conditions for loading, empty, and populated views. The exercise reinforces basic rendering mechanics and favors clear branches over increasingly nested expressions as interface states grow.',
  },
  {
    id: 'react-lists', title: 'Stable keys help React follow items through a changing list',
    url: 'https://react.dev/learn/rendering-lists', publisher: 'React',
    topics: ['web'], concepts: ['stable React keys', 'array rendering', 'list identity'], minutes: 3,
    text: 'Rendering a list in React usually starts with mapping an array into components. Stable keys identify items across updates, which matters when entries are inserted, removed, or reordered. The documentation explains why identity should come from the data rather than an arbitrary value generated during rendering. Try sorting a list of editable rows while preserving each row’s contents to see why this matters. This is a useful foundational check for any feed interface, though it will be familiar to a developer who already builds dynamic React lists.',
    summary: 'Use stable data identities when mapping arrays into React components. Reordering editable rows demonstrates why keys matter, while experienced developers may only need a quick implementation check.',
  },
  {
    id: 'react-state', title: 'Keep interactive values in React state',
    url: 'https://react.dev/learn/state-a-components-memory', publisher: 'React',
    topics: ['web'], concepts: ['React state', 'state setters', 'component memory'], minutes: 3,
    text: 'React state preserves component information between renders and provides an update mechanism. The introductory state guide contrasts this behavior with ordinary local variables that do not trigger the same rendering workflow. A simple gallery can store the current image index and update it from a button handler. Follow that exercise to understand how a component remembers an interaction. For a builder already comfortable with state and event handlers, the practical value is usually a concise refresher before moving to more specific questions about shared state or asynchronous updates.',
    summary: 'Learn how state preserves interactive values and requests a new render. A gallery exercise teaches the foundation, while experienced builders can compress it before studying harder state coordination problems.',
  },
  {
    id: 'react-effects', title: 'Use an Effect to synchronize with an external system',
    url: 'https://react.dev/learn/synchronizing-with-effects', publisher: 'React',
    topics: ['web'], concepts: ['React effects', 'effect cleanup', 'external synchronization'], minutes: 4,
    text: 'Effects synchronize React components with systems outside the rendering calculation. The React guide uses examples such as controlling media and connecting to a service, while explaining dependencies and cleanup. A useful practice task is to connect a component to a subscription and ensure it disconnects when no longer needed. Avoid treating every derived value as a reason to add another Effect. If the developer already understands this distinction, the introductory lesson is familiar; a real bug involving stale subscriptions would provide a more targeted reason to revisit it.',
    summary: 'Use Effects for external synchronization and clean up subscriptions when their lifetime ends. This familiar foundation becomes most useful when tied to a concrete dependency or lifecycle bug.',
  },
  {
    id: 'react-memo', title: 'Cache an expensive calculation only when it helps',
    url: 'https://react.dev/reference/react/useMemo', publisher: 'React',
    topics: ['web'], concepts: ['React memoization', 'dependency arrays', 'render performance'], minutes: 4,
    text: 'The useMemo Hook can cache a calculation between renders while its dependencies remain unchanged. React presents it as a performance optimization, not a semantic guarantee that application correctness should depend on. Start with a working component and measure whether a calculation is actually expensive before introducing caching. A small filtering exercise can show the relationship between inputs, dependencies, and recomputation. This reference is useful during a measured performance investigation, but reading it repeatedly will not substitute for profiling the application that feels slow to its users.',
    summary: 'Treat useMemo as a measured optimization for expensive calculations. Keep dependencies accurate and application correctness independent of the cache, then use profiling to decide whether the added complexity helps.',
  },
  {
    id: 'next-components', title: 'Choose the server or client boundary for each component',
    url: 'https://nextjs.org/docs/app/getting-started/server-and-client-components', publisher: 'Next.js',
    topics: ['web'], concepts: ['Server Components', 'client interaction state', 'server-only secrets'], minutes: 4,
    text: 'Next.js distinguishes components rendered on the server from client components that support interactive browser behavior. The documentation explains when to use each and how to establish a client boundary. A practical beginner exercise keeps data access on the server while moving a small interactive control into a client component. This introduces a useful architectural vocabulary for web applications and reinforces that provider secrets belong in server-owned code. For someone who already uses these boundaries daily, the broad overview can be compressed until a specific composition or serialization issue arises.',
    summary: 'Keep server-owned data access separate from browser interactions and establish a small client boundary. The overview is foundational, so experienced Next.js builders may need only its relevant edge cases.',
  },
  {
    id: 'css-subgrid', title: 'Align nested cards with CSS subgrid',
    url: 'https://developer.mozilla.org/en-US/docs/Web/CSS/Guides/Grid_layout/Subgrid', publisher: 'MDN',
    topics: ['web', 'design'], concepts: ['CSS subgrid', 'shared grid tracks', 'nested layout alignment'], minutes: 4,
    text: 'CSS subgrid lets a nested grid participate in tracks defined by its parent. This is useful when card headings, descriptions, and actions should align across neighboring cards even though their contents differ in length. Build a pricing table with uneven descriptions and compare independent nested grids with a shared track structure. The technique solves a layout problem rather than a content intelligence problem. It belongs in a frontend polish session when alignment is visibly broken, and can wait when the immediate task is validating whether recommendations help a learner.',
    summary: 'Use subgrid to align internal card sections across a parent grid. It is a focused layout technique that becomes valuable when uneven content makes a comparison interface hard to scan.',
  },
  {
    id: 'view-transitions', title: 'Animate a change of view without losing visual continuity',
    url: 'https://developer.mozilla.org/en-US/docs/Web/API/View_Transition_API', publisher: 'MDN',
    topics: ['web', 'design'], concepts: ['View Transition API', 'visual continuity', 'transition snapshots'], minutes: 5,
    text: 'The View Transition API provides a mechanism for animating changes between views. Developers can use it to preserve visual continuity when content changes rather than constructing every transition manually. A small gallery is a suitable experiment: select a thumbnail, expand its detail view, and make the relationship between the two states visible. Design a reduced-motion experience as well, and verify that navigation remains functional without the animation. The technique improves presentation, but it should accompany an understandable state change rather than conceal a delayed operation behind decorative movement.',
    summary: 'Use view transitions to make related interface states visually connected. Keep navigation functional without animation and provide reduced motion, so the effect explains a change rather than masking delay.',
  },
  {
    id: 'apple-motion', title: 'Motion should explain what changed',
    url: 'https://developer.apple.com/design/human-interface-guidelines/motion', publisher: 'Apple',
    topics: ['design'], concepts: ['purposeful interface motion', 'status feedback', 'reduced motion'], minutes: 4,
    text: 'Apple’s motion guidance connects animation with feedback, status, instruction, and continuity. This gives a designer a practical review question: what does a movement help the user understand? A selected card can expand into its details, while a completed operation can settle into a stable result. Repeatedly animating unrelated decoration adds activity without necessarily adding information. Prototype the transition with keyboard input and reduced-motion settings before polishing it. The aim is an interface whose changing state remains understandable even when an animation is shortened, simplified, or removed.',
    summary: 'Connect animation to status and interface relationships. Review each movement for its explanatory purpose, then test keyboard and reduced-motion experiences so essential meaning does not depend on visual effects.',
  },
  {
    id: 'apple-materials', title: 'Translucent materials need a reason beyond looking glossy',
    url: 'https://developer.apple.com/design/human-interface-guidelines/materials', publisher: 'Apple',
    topics: ['design'], concepts: ['semantic materials', 'translucent hierarchy', 'material contrast'], minutes: 4,
    text: 'Apple describes materials as a way to express structure and hierarchy in an interface. Their appearance can depend on surrounding content and system settings, so choosing one only for a particular color is fragile. For a product prototype, a translucent toolbar might suggest a control layer above content, while the reading surface stays quiet and legible. Test the material over both light and dark backgrounds and inspect label contrast. If the treatment reduces readability or blurs the distinction between content and controls, a simpler solid surface may communicate the hierarchy better.',
    summary: 'Choose materials for their role in interface hierarchy and test their contrast across backgrounds. Translucency should clarify the relationship between controls and content while preserving dependable readability.',
  },
  {
    id: 'webgpu', title: 'Move suitable browser workloads onto the GPU',
    url: 'https://developer.mozilla.org/en-US/docs/Web/API/WebGPU_API', publisher: 'MDN',
    topics: ['web'], concepts: ['WebGPU compute', 'GPU command submission', 'browser graphics'], minutes: 8,
    text: 'WebGPU exposes modern graphics and computation capabilities to web applications. Its model includes devices, buffers, pipelines, and commands that describe work for a GPU. A developer exploring visual simulations can begin with a small rendering or compute example and measure the full cost of transferring data and presenting results. This is a specialized engineering investment with its own compatibility and resource considerations. It may become useful for a demanding visualization, but it is usually an adjacent research topic when the immediate product question concerns whether a learner finds a recommendation valuable.',
    summary: 'Explore WebGPU when graphics or parallel computation creates a concrete browser bottleneck. Measure complete workload costs and compatibility instead of adopting GPU infrastructure before a product requires it.',
  },
  {
    id: 'wasm', title: 'WebAssembly brings a portable compilation target to the browser',
    url: 'https://webassembly.org/docs/high-level-goals/', publisher: 'WebAssembly',
    topics: ['web'], concepts: ['WebAssembly compilation', 'portable binary modules', 'host interoperability'], minutes: 6,
    text: 'WebAssembly defines a portable binary format designed to support efficient execution in a sandboxed environment. Its goals include interoperability with the surrounding web platform rather than replacing all JavaScript. A useful project is to compile a small existing library and compare integration effort, startup time, and workload performance against a JavaScript implementation. The outcome depends on the actual task and data crossing the boundary. This is valuable systems knowledge for a builder with a suitable workload, but it does not automatically improve the relevance or learning impact of a content feed.',
    summary: 'Evaluate WebAssembly for a concrete library or computation that benefits from compilation. Include startup and interoperability costs in the comparison rather than assuming a different execution format improves the product.',
  },
  {
    id: 'pwa', title: 'Make a web experience usable after the connection disappears',
    url: 'https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps', publisher: 'MDN',
    topics: ['web', 'design'], concepts: ['progressive web apps', 'offline interaction', 'installable web experiences'], minutes: 6,
    text: 'Progressive web apps combine web delivery with capabilities that can support more app-like experiences. MDN’s overview introduces concerns such as installation and offline behavior. A practical prototype should define what remains usable without a network: already saved pages may be available even when new model requests cannot run. Make this distinction visible and avoid presenting stale data as freshly synchronized. Start with one complete offline task, test it with the connection disabled, and verify how the interface recovers when connectivity returns before expanding the caching strategy.',
    summary: 'Define one complete offline task and test its recovery when connectivity returns. A progressive web experience should distinguish saved content from operations that still require a live network connection.',
  },
  {
    id: 'websockets', title: 'A live connection still needs flow control and lifecycle handling',
    url: 'https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API', publisher: 'MDN',
    topics: ['web'], concepts: ['WebSocket connections', 'message backpressure', 'connection lifecycle'], minutes: 5,
    text: 'WebSockets support two-way communication between a browser and a server over a persistent connection. The API is useful for live updates, but application code still needs to handle disconnects, reconnection behavior, and incoming message volume. MDN notes the lack of built-in backpressure in the standard WebSocket interface. Build a small status dashboard and deliberately interrupt its connection before adopting the transport for a larger product. A live socket is an implementation choice; users benefit when the information stays accurate and the interface clearly explains whether updates are still arriving.',
    summary: 'Treat a persistent connection as a transport with failure and flow-control concerns. Test interrupted updates and message volume so the interface communicates freshness rather than merely appearing live.',
  },
  {
    id: 'typescript-narrowing', title: 'Describe asynchronous states with a discriminated union',
    url: 'https://www.typescriptlang.org/docs/handbook/2/narrowing.html', publisher: 'TypeScript',
    topics: ['web'], concepts: ['TypeScript narrowing', 'discriminated unions', 'exhaustive state handling'], minutes: 4,
    text: 'TypeScript narrows types as code checks values and follows control flow. Discriminated unions use a shared field with distinct literal values to represent alternatives clearly. An asynchronous interface can model idle, loading, success, and failure as separate cases, with result data only present for success. This reduces the number of impossible combinations a developer must remember while rendering. Practice by replacing several independent boolean flags with one state union, then check every branch. The technique improves implementation clarity but remains supporting infrastructure rather than a new recommendation capability.',
    summary: 'Use discriminated unions to represent asynchronous states and make impossible combinations harder to express. Explicit branches help interface code handle success and failure without coordinating unrelated boolean flags.',
  },
  {
    id: 'postgres-indexes', title: 'An index speeds some reads and adds work to writes',
    url: 'https://www.postgresql.org/docs/current/indexes-intro.html', publisher: 'PostgreSQL',
    topics: ['web'], concepts: ['database indexes', 'read-write tradeoffs', 'query access paths'], minutes: 5,
    text: 'PostgreSQL indexes provide additional access paths that can make selected queries faster. The documentation also explains their cost: indexes require storage and must be maintained as table contents change. Before adding one, identify the exact slow query and inspect its behavior with representative data. A small experiment can compare lookup latency and insertion cost before and after indexing a frequently filtered column. This is important once persistence becomes a measured bottleneck, but speculative indexing is unlikely to answer whether a product’s ranking policy is useful to its first users.',
    summary: 'Add indexes in response to observed query patterns and measure their write and storage costs. The right access path depends on real workload behavior rather than a blanket indexing rule.',
  },
  {
    id: 'postgres-json', title: 'Choose JSON storage deliberately instead of hiding every field in a blob',
    url: 'https://www.postgresql.org/docs/current/datatype-json.html', publisher: 'PostgreSQL',
    topics: ['web'], concepts: ['PostgreSQL jsonb', 'JSON storage semantics', 'structured document queries'], minutes: 6,
    text: 'PostgreSQL supports JSON data with different storage and processing characteristics for json and jsonb. Its documentation explains their semantics, operators, and indexing options. Flexible documents can be convenient for evolving metadata, while frequently constrained fields may still deserve explicit relational structure. Prototype the queries the product actually needs, such as filtering event attributes or updating one setting, before choosing a representation. The useful engineering question is not whether JSON is modern, but whether the chosen structure keeps validation, access patterns, and future migrations understandable for the application.',
    summary: 'Match JSON storage to actual validation and query needs. Flexible metadata is useful, but explicit relational fields and document structures should be chosen according to access patterns and maintainability.',
  },
  {
    id: 'sqlite-wal', title: 'Understand what SQLite write-ahead logging changes',
    url: 'https://sqlite.org/wal.html', publisher: 'SQLite',
    topics: ['web'], concepts: ['SQLite write-ahead logging', 'checkpointing', 'database concurrency'], minutes: 6,
    text: 'SQLite write-ahead logging records changes in a separate log before checkpointing them into the database. The documentation describes how this affects readers, writers, and operational constraints. For a local application, understanding checkpoints and concurrent access can explain behavior that is surprising when viewed as simple file writes. Create a small workload with reading and writing processes and observe it before changing configuration. The topic matters for reliable persistence and backup procedures, but enabling one journal mode does not replace thinking through data ownership, deployment assumptions, or recovery after interruption.',
    summary: 'Study WAL as a change to persistence and concurrency behavior, including checkpoints and operational constraints. Validate it with a representative workload instead of treating a configuration toggle as complete reliability.',
  },
  {
    id: 'docker-build', title: 'A container image should be reproducible from its build inputs',
    url: 'https://docs.docker.com/build/concepts/overview/', publisher: 'Docker',
    topics: ['web'], concepts: ['Docker build context', 'image layers', 'build reproducibility'], minutes: 5,
    text: 'Docker Build turns a build definition and context into a container image. The overview introduces the components involved in executing builds and producing reusable artifacts. A practical exercise packages a small server, then verifies which files enter the build context and which dependencies are installed. Keep secrets out of image layers and check that another machine can reproduce the intended runtime. Containerization can help distribution, but it adds its own maintenance concerns and should follow a concrete deployment need rather than become a prerequisite for testing a small product idea.',
    summary: 'Package a server with explicit build inputs and inspect what enters the image. Reproducibility and secret handling matter more than introducing containers before there is a concrete deployment need.',
  },
  {
    id: 'kubernetes-deployments', title: 'A Deployment reconciles desired replicas with a running cluster',
    url: 'https://kubernetes.io/docs/concepts/workloads/controllers/deployment/', publisher: 'Kubernetes',
    topics: ['web'], concepts: ['Kubernetes Deployments', 'declarative rollout', 'replica reconciliation'], minutes: 8,
    text: 'Kubernetes Deployments describe desired application state and manage ReplicaSets during updates. The documentation explains rollout behavior, scaling, and related status information. A learning exercise changes a container image and observes how replicas transition while the controller works toward the declared state. This is useful operational knowledge for a service that already needs cluster orchestration. A founder building an early local prototype may have more immediate questions about user value, data quality, and distribution, so cluster mechanics can remain a later study topic until deployment complexity makes them relevant.',
    summary: 'Learn how declarative deployments manage replicas and rollouts when cluster operations become necessary. For an early prototype, this infrastructure study may be less urgent than validating user value and distribution.',
  },
  {
    id: 'prometheus-metrics', title: 'A counter, a gauge, and a latency histogram answer different questions',
    url: 'https://prometheus.io/docs/concepts/metric_types/', publisher: 'Prometheus',
    topics: ['web'], concepts: ['metric type semantics', 'latency histograms', 'counters and gauges'], minutes: 5,
    text: 'Prometheus distinguishes metric types such as counters, gauges, histograms, and summaries. Choosing the right type determines which questions a measurement can answer. Completed requests naturally suggest a counter, current queue depth a gauge, and response durations a distribution. Start with the operational decision a chart should support before instrumenting every available value. In a prototype, a small number of clear measurements can reveal slow calls or growing backlogs. A sophisticated dashboard remains secondary if nobody has yet established that the underlying product solves an important user problem.',
    summary: 'Choose metric types according to the operational question: totals, current levels, and duration distributions differ. A few interpretable measurements can be more useful than a dashboard full of ambiguous numbers.',
  },
  {
    id: 'd3-scales', title: 'A chart scale is a mapping decision, not decoration',
    url: 'https://d3js.org/d3-scale', publisher: 'D3',
    topics: ['web', 'design'], concepts: ['D3 scales', 'data domains', 'visual encodings'], minutes: 4,
    text: 'D3 scales map values from a data domain into a visual range. Different scale families support numerical, categorical, and other kinds of input, giving a chart a deliberate relationship between data and presentation. Build a small bar chart and inspect what happens when the domain changes or categories are added. Labels and axis choices should help the reader interpret that mapping accurately. This is a focused visualization skill: attractive motion and color cannot compensate for a scale that exaggerates a difference or hides the meaning of the underlying measurement.',
    summary: 'Choose chart mappings deliberately and inspect their behavior as data changes. Clear domains, labels, and visual ranges make a quantitative display interpretable before animation or styling adds polish.',
  },
  {
    id: 'variable-fonts', title: 'Variable fonts expose a range of typography inside one font resource',
    url: 'https://developer.mozilla.org/en-US/docs/Web/CSS/Guides/Fonts/Variable_fonts', publisher: 'MDN',
    topics: ['design', 'web'], concepts: ['variable font axes', 'font weight interpolation', 'typographic hierarchy'], minutes: 4,
    text: 'Variable fonts can represent multiple styles through adjustable axes within a font resource. MDN explains common axes and how CSS can control the available range. A typography experiment can compare a small set of weight choices across headings, labels, and body text without changing the underlying family. Check actual font support and readable results instead of assuming every axis is available in every font. This can refine an interface’s hierarchy and loading strategy, but it is usually a polish task after content structure and important interactions already work well.',
    summary: 'Explore supported font axes to build a consistent typographic hierarchy. Check real rendering and available ranges, keeping typography improvements in service of readable content and functional interface structure.',
  },
  {
    id: 'figma-layout', title: 'Auto layout helps a design survive changing content',
    url: 'https://help.figma.com/hc/en-us/articles/360040451373-Guide-to-auto-layout', publisher: 'Figma',
    topics: ['design'], concepts: ['Figma auto layout', 'content-driven sizing', 'layout constraints'], minutes: 4,
    text: 'Figma auto layout organizes objects using rules for direction, spacing, and resizing. Instead of manually repositioning every element, a designer can test how a component responds to longer text or additional content. Build a button, a card, and a small list with varied labels, then resize their containing frame. The exercise reveals assumptions that fixed mockups often hide. It is valuable for communicating resilient interface behavior to a developer, though a tidy design file alone cannot show whether the real application loads data correctly or responds to feedback.',
    summary: 'Use auto layout to test components with longer text, extra content, and changing container sizes. Constraint-based designs communicate adaptable behavior more effectively than a collection of manually positioned mockups.',
  },
  {
    id: 'framer-cms', title: 'Separate repeatable content from its page layout',
    url: 'https://www.framer.com/academy/lessons/getting-started-with-the-framer-cms', publisher: 'Framer',
    topics: ['design', 'web'], concepts: ['Framer CMS collections', 'content field schemas', 'reusable detail pages'], minutes: 4,
    text: 'Framer CMS organizes repeated content into collections, items, and fields that connect to page layouts. A collection can hold articles or case studies while a reusable detail page presents each record through the same structure. Prototype a small resource library by defining its title, description, image, and source link fields before styling the page. This makes updates easier to propagate consistently across the site. It is a useful publishing workflow, but a CMS by itself does not infer reader knowledge, evaluate learning value, or decide which resource belongs first.',
    summary: 'Model repeatable content with collections and fields, then connect it to reusable layouts. This supports consistent publishing while leaving personalization and recommendation policy to separate product logic.',
  },
  {
    id: 'contrast', title: 'Subtle text still needs enough contrast to read',
    url: 'https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum.html', publisher: 'W3C WAI',
    topics: ['design', 'web'], concepts: ['WCAG text contrast', 'relative luminance', 'readable secondary labels'], minutes: 4,
    text: 'WCAG’s minimum contrast guidance explains how text contrast supports readers with reduced visual acuity or contrast sensitivity. A minimalist interface can fail this basic task when secondary labels become too pale against their background. Check actual foreground and background combinations, including hover states and translucent surfaces, instead of judging contrast from a design screenshot alone. Small metadata deserves attention because it often explains timing, source, or status. Improving legibility may produce less dramatic visual change than an animation, but it directly affects whether people can understand the information being presented.',
    summary: 'Measure text contrast across actual interface states, especially pale metadata and translucent surfaces. Minimal styling remains useful only when readers can understand the source, status, and timing information it contains.',
  },
];

export const BURST_CORPUS: ContentItem[] = briefs.map(brief => ({
  id: `burst-${brief.id}`,
  title: brief.title,
  url: brief.url,
  publisher: `${brief.publisher} · briefing`,
  kind: brief.kind ?? 'documentation',
  text: brief.text,
  addedAt: '2026-09-26T00:00:00.000Z',
  provenance: 'editorial-brief',
  analysis: {
    summary: brief.summary,
    concepts: brief.concepts,
    topics: brief.topics,
    evidence: [{
      quote: brief.text.split(/(?<=\.)\s+/)[0],
      insight: 'Supporting sentence from this original editorial brief, not a quotation from the linked publisher.',
    }],
    // Editorial estimate for exploring the linked resource, not timed comprehension data.
    readingMinutes: brief.minutes,
    source: 'editorial',
    model: 'burst-editorial-v1',
  },
  decision: null,
  feedback: null,
  status: 'ready',
  error: null,
}));
