import {execFileSync} from 'node:child_process'; import {readFileSync,writeFileSync,existsSync} from 'node:fs'; import {resolve,dirname} from 'node:path'; import {createHash} from 'node:crypto';
const dir=dirname(new URL(import.meta.url).pathname),extract=readFileSync(resolve(dir,'commons-extract.js'),'utf8');
const seeds=['https://commons.wikimedia.org/wiki/Category:Portrait_photographs_of_actors','https://commons.wikimedia.org/wiki/Category:Portrait_photographs_of_actresses'];
const queue=seeds.map(url=>({url,depth:0})),seen=new Set(),files=new Map(),reports=[]; const maxFiles=Number(process.env.COMMONS_MAX_FILES||380);
function browser(args,input){return execFileSync('npx',['--yes','agent-browser','--session','expand-portraits',...args],{encoding:'utf8',input,maxBuffer:10*1024*1024,timeout:60000});}
function visit(url){const name='commons-'+createHash('sha256').update(url).digest('hex').slice(0,16)+'.json';const path=resolve(dir,'evidence',name);if(existsSync(path))return JSON.parse(readFileSync(path,'utf8'));browser(['open',url]);const data=JSON.parse(JSON.parse(browser(['eval','--stdin'],extract)));writeFileSync(path,JSON.stringify(data,null,2)+'\n');return data;}
for(let i=0;i<queue.length&&files.size<maxFiles;i++){
 const {url,depth}=queue[i];if(seen.has(url))continue;seen.add(url);try{const page=visit(url);for(const f of page.files){if(!f.url||!/\.(jpe?g|png|webp)$/i.test(decodeURIComponent(f.url)))continue;if(!files.has(f.url))files.set(f.url,{...f,category:page.title.replace(/^Category:/,''),listingUrl:page.url});}reports.push({url,type:'category',files:page.files.length,totalUnique:files.size}); console.log(JSON.stringify(reports.at(-1)));for(const next of page.next)queue.push({url:next,depth}); if(depth<1)for(const sub of page.subcategories)if(/portrait|head shot/i.test(sub.label))queue.push({url:sub.url,depth:depth+1});}catch(error){reports.push({url,error:error.message.slice(0,150)});}}
const selected=[...files.values()].slice(0,maxFiles),result=[];
for(const file of selected){try{const page=visit(file.url);if(page.imageUrl&&page.licenseShort.length)result.push({...page,listingUrl:file.listingUrl,category:file.category});reports.push({url:file.url,type:'file',license:page.licenseShort,accepted:!!page.imageUrl&&!!page.licenseShort.length,total:result.length}); if(result.length%20===0)console.log(JSON.stringify(reports.at(-1)));}catch(error){reports.push({url:file.url,error:error.message.slice(0,150)});}writeFileSync(resolve(dir,'commons-portraits-raw.json'),JSON.stringify(result,null,2)+'\n');writeFileSync(resolve(dir,'commons-crawl-report.json'),JSON.stringify({reports,selected: selected.length},null,2)+'\n');}
browser(['screenshot',resolve(dir,'evidence/commons-portrait-file.png')]);
