import {readFileSync,writeFileSync,readdirSync} from 'node:fs';import {resolve,dirname} from 'node:path';
const dir=dirname(new URL(import.meta.url).pathname),evidence=resolve(dir,'evidence');
const pages=readdirSync(evidence).filter(f=>/^netflix-\d+\.json$/.test(f)).map(f=>JSON.parse(readFileSync(resolve(evidence,f),'utf8'))).sort((a,b)=>a.observedAt.localeCompare(b.observedAt));
const all=new Map();
for(const page of pages)for(const card of page.cards){const id=card.url.match(/title\/(\d+)/)?.[1];if(!id||!card.title)continue;const list=all.get(id)||[];list.push({page,card});all.set(id,list)}
const groups={movies:[],series:[],anime:[]};const chosen=new Map();
for(const [id,observations]of all){const animations=observations.filter(o=>/anime|animat|cartoon/i.test(o.page.heading));const explicitMovie=observations.filter(o=>/movies|films/i.test(o.card.section)&&!/tv|shows|series/i.test(o.card.section));const explicitSeries=observations.filter(o=>/tv|shows|series/i.test(o.card.section)&&!/movies|films/i.test(o.card.section));const kind=animations.length?'anime':explicitSeries.length>explicitMovie.length?'series':explicitMovie.length?'movies':observations[0].page.kind;const primary=(animations.length?animations:kind==='series'&&explicitSeries.length?explicitSeries:kind==='movies'&&explicitMovie.length?explicitMovie:observations)[0];chosen.set(id,{kind,primary,observations});groups[kind].push(id);}
const labels={movies:'Movies',series:'TV series & shows',anime:'Anime & animation'};const summary={uniqueTitles:all.size,pages:pages.length,kinds:{},classificationConflicts:0};
for(const kind of Object.keys(groups)){
 const sourceId=`netflix-${kind}`;const allID=`netflix-${kind}-all`;const related=pages.filter(page=>[...groups[kind]].some(id=>chosen.get(id).observations.some(o=>o.page.url===page.url)));
 const chosenPages=related.filter(p=>p.kind===kind||kind==='anime'&&/anime|animat|cartoon/i.test(p.heading)).slice(0,24);
 const collections=[{id:allID,title:`Netflix · ${labels[kind]}`,kind,description:'Unique titles actually observed on Netflix public genre pages. Browser-visible catalogue discovery, not a guarantee of playback availability for a subscription or region.'},...chosenPages.map(p=>({id:`netflix-${kind}-g${p.url.match(/genre\/(\d+)/)[1]}`,title:`Netflix · ${p.heading}`,kind,description:`${labels[kind]} items observed on the public Netflix “${p.heading}” page. Source category membership is retained; format classification is based on observed catalogue sections.`}))];
 const items=groups[kind].map(id=>{const {primary,observations}=chosen.get(id);const c=primary.card,p=primary.page;const movieSeen=observations.some(o=>/movies|films/i.test(o.card.section)),tvSeen=observations.some(o=>/tv|shows|series/i.test(o.card.section));if(movieSeen&&tvSeen)summary.classificationConflicts++;const membership=chosenPages.filter(page=>observations.some(o=>o.page.url===page.url)).map(page=>`netflix-${kind}-g${page.url.match(/genre\/(\d+)/)[1]}`);return {sourceId,externalId:id,kind,collectionIds:[allID,...membership].slice(0,30),title:c.title,url:`https://www.netflix.com/title/${id}`,imageUrl:c.imageUrl,description:`Listed by Netflix in “${c.section}” on the “${p.heading}” public catalogue page.`,observedAt:p.observedAt,listingUrl:p.url,attributes:{provider:'Netflix',observedSection:c.section,observedGenrePages:[...new Set(observations.map(o=>o.page.heading))].join(' · ').slice(0,2000),classificationBasis:kind==='anime'?'Observed on Netflix anime, animation or cartoons genre page':'Majority of explicit movie versus TV/series row labels across observed Netflix pages; catalogue grouping, not a detail-page format audit',availabilityScope:'Public website discovery only; region, subscription and current playback availability unverified',sourceRank:c.position},extraction:'browser-dom'};});
 const used=new Set(items.flatMap(i=>i.collectionIds));const batch={source:{id:sourceId,label:`Netflix public catalogue · ${labels[kind]}`,homeUrl:'https://www.netflix.com/',kind,status:'partial',checkedAt:pages.at(-1).observedAt,note:'Collected from rendered official Netflix public genre pages and their observed genre links, without authentication or hidden APIs. Netflix title IDs deduplicated globally across all three screen batches. Posters are observed remote URLs; rights remain with their owners. Public listings are not a verified full or region-specific playback inventory. Classification is catalogue-based; anime includes Western animation. Snapshot only.'},collections:collections.filter(c=>used.has(c.id)),items};writeFileSync(resolve(dir,`netflix-${kind}.json`),JSON.stringify(batch,null,2)+'\n');summary.kinds[kind]={items:items.length,collections:batch.collections.length,images:items.filter(i=>i.imageUrl).length};
}
writeFileSync(resolve(dir,'netflix-normalization-report.json'),JSON.stringify(summary,null,2)+'\n');console.log(JSON.stringify(summary,null,2));
