import { useState, type FormEvent } from 'react';
import type { PersonalProfileFact, PersonalSnapshot } from '../domain/personal';
import { PersonalDialog, PersonalError, PersonalIcon as Icon } from './PersonalShared';
import { personalRequest, relativeDate } from './personal-utils';

export default function PersonalMemory({ snapshot, refresh }: { snapshot: PersonalSnapshot; refresh: () => Promise<void> }) {
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const [editing, setEditing] = useState<PersonalProfileFact | 'new' | null>(null);
  const [kind, setKind] = useState<PersonalProfileFact['kind']>('knowledge');
  const [value, setValue] = useState('');
  const [domain, setDomain] = useState('content');
  const [deleting, setDeleting] = useState<{ type: 'sessions' | 'datasets' | 'facts'; id: string; title: string } | null>(null);
  const [filter, setFilter] = useState<PersonalProfileFact['kind'] | 'all'>('all');
  const [notice, setNotice] = useState('');
  async function run(action: () => Promise<void>) { setBusy(true); setError(''); try { await action(); } catch (e) { setError(e instanceof Error ? e.message : 'Could not update your memory.'); } finally { setBusy(false); } }
  function edit(fact?: PersonalProfileFact) { setEditing(fact || 'new'); setKind(fact?.kind || 'knowledge'); setValue(fact?.value || ''); setDomain(fact?.domain || 'content'); }
  async function save(event: FormEvent) {
    event.preventDefault(); if (!value.trim()) return;
    await run(async () => { await personalRequest(editing === 'new' ? '/facts' : `/facts/${editing!.id}`, { kind, value: value.trim(), domain }, editing === 'new' ? 'POST' : 'PUT'); await refresh(); setEditing(null); setNotice('Memory updated. Future rankings use the corrected record.'); });
  }
  const facts = snapshot.facts.filter(fact => filter === 'all' || fact.kind === filter);
  const activeComparisons = snapshot.comparisons.filter(item => !item.undone);
  return <div className="p-memory-page"><header className="p-page-heading"><span className="p-eyebrow">YOUR INTELLIGENCE, IN YOUR HANDS</span><div><h1>A memory you can inspect.</h1><a className="vr-button vr-button-secondary" href="/api/personal/export" download><Icon name="download" size={15} />Export your data</a></div><p>What you know. What you choose. What matters to you. A record you can always correct.</p></header><PersonalError error={error} dismiss={() => setError('')} />{notice && <div className="p-memory-notice" role="status"><Icon name="check" size={15} />{notice}<button onClick={() => setNotice('')} aria-label="Dismiss notification"><Icon name="close" size={13} /></button></div>}
    <section className="p-memory-stats"><div><Icon name="compare" /><strong>{snapshot.trainingCount}</strong><span>training comparisons</span></div><div><Icon name="memory" /><strong>{snapshot.models.length}</strong><span>domain models</span></div><div><Icon name="known" /><strong>{snapshot.facts.filter(fact => fact.kind === 'knowledge').length}</strong><span>known concepts</span></div><div><Icon name="source" /><strong>{snapshot.testCount}</strong><span>blind test choices</span></div></section>
    <section className="p-memory-section"><div className="p-section-head"><div><h2>What you’ve told your engine</h2><p>Knowledge and stated priorities. Scoped to where they apply.</p></div><button className="vr-button vr-button-secondary" onClick={() => edit()}><Icon name="edit" size={14} />Add a memory</button></div><div className="p-memory-filters">{([{ id: 'all', label: 'Everything' }, { id: 'knowledge', label: 'Knowledge' }, { id: 'preference', label: 'Preferences' }, { id: 'value', label: 'Values' }] as const).map(item => <button className={filter === item.id ? 'active' : ''} key={item.id} onClick={() => setFilter(item.id)}>{item.label}<span>{snapshot.facts.filter(fact => item.id === 'all' || fact.kind === item.id).length}</span></button>)}</div><div className="p-facts">{facts.length ? facts.map(fact => <article key={fact.id}><span className={`p-fact-icon ${fact.kind}`}><Icon name={fact.kind === 'knowledge' ? 'known' : fact.kind === 'preference' ? 'compare' : 'spark'} size={19} /></span><div><div className="p-fact-meta"><span>{fact.kind}</span><span>{fact.domain}</span><span>{fact.source === 'stated' ? 'You stated this' : 'Inferred · correctable'}</span></div><h3>{fact.value}</h3><details><summary>{fact.supportingEventIds.length} supporting {fact.supportingEventIds.length === 1 ? 'event' : 'events'} · Updated {relativeDate(fact.updatedAt)}</summary><p>{fact.source === 'stated' ? 'This record came from an explicit statement or a known-concept action.' : `An inferred record with confidence ${Math.round(fact.confidence * 100)}%. It may be wrong; edit or delete it.`}</p>{fact.supportingEventIds.length > 0 && <ul>{fact.supportingEventIds.map(id => { const choice = snapshot.comparisons.find(item => item.id === id); return <li key={id}><code>{id}</code>{choice && <span>Choice: {choice.choice}{choice.reason ? ` · ${choice.reason}` : ''}</span>}</li>; })}</ul>}</details></div><div className="p-fact-actions"><button onClick={() => edit(fact)} aria-label={`Edit ${fact.value}`}><Icon name="edit" size={15} /></button><button onClick={() => setDeleting({ type: 'facts', id: fact.id, title: fact.value })} aria-label={`Delete ${fact.value}`}><Icon name="trash" size={15} /></button></div></article>) : <div className="p-empty"><Icon name="memory" size={24} /><h3>Room for what makes you, you.</h3><p>Add something you already know or a tradeoff that matters to you.</p></div>}</div></section>
    <section className="p-memory-section"><div className="p-section-head"><div><h2>What your choices are teaching</h2><p>Actual learned weights, separated by domain. These describe the model, not your identity.</p></div></div>{snapshot.models.length ? <div className="p-model-grid">{snapshot.models.map(model => { const weights = model.weights.map((weight, index) => ({ name: model.featureNames[index], weight })).sort((a, b) => Math.abs(b.weight) - Math.abs(a.weight)).slice(0, 6); const max = Math.max(...weights.map(item => Math.abs(item.weight)), 0.1); return <article className="p-model-card" key={model.id}><div><span className="p-eyebrow">{model.domain.replaceAll('-', ' ')}</span><span>v{model.version}</span></div><h3>{model.trainingCount} choices, one point of view.</h3><p>Weight changes reflect explicit training comparisons. Positive values raise items with that feature.</p><div className="p-weight-list">{weights.map(item => <div key={item.name}><span>{item.name.replace(/([A-Z])/g, ' $1').replaceAll('-', ' ')}<b>{item.weight >= 0 ? '+' : ''}{item.weight.toFixed(3)}</b></span><div><i className={item.weight < 0 ? 'negative' : ''} style={{ width: `${Math.abs(item.weight) / max * 50}%` }} /></div></div>)}</div><details><summary>Inspect all weights and feature schema</summary><code>{model.schemaId}</code><dl>{model.featureNames.map((feature, index) => <div key={feature}><dt>{feature}</dt><dd>{model.weights[index]?.toFixed(6)}</dd></div>)}</dl></details></article>; })}</div> : <div className="p-model-empty"><Icon name="compare" size={24} /><div><h3>Your first choice starts the model.</h3><p>Compare information cards or choose a collection in Arena.</p></div><a href="#arena" className="vr-button vr-button-secondary">Open Arena<Icon name="arrow" size={14} /></a></div>}</section>
    <section className="p-memory-section"><div className="p-section-head"><div><h2>Your comparison record</h2><p>Undo removes a comparison from training and rebuilds the affected model.</p></div><span>{activeComparisons.length} active</span></div><div className="p-comparison-ledger">{activeComparisons.slice().reverse().slice(0, 30).map(comparison => <article key={comparison.id}><span className="p-ledger-choice">{comparison.choice === 'a' || comparison.choice === 'b' ? comparison.choice.toUpperCase() : comparison.choice === 'tie' ? '=' : comparison.choice === 'neither' ? '∅' : '—'}</span><div><strong>{comparison.choice === 'a' || comparison.choice === 'b' ? `Chose ${comparison.choice.toUpperCase()}` : comparison.choice === 'tie' ? 'Equally good' : comparison.choice === 'neither' ? 'Neither' : 'Skipped'}</strong><p>{comparison.reason || 'No reason added.'}</p><small>{relativeDate(comparison.createdAt)} · {comparison.id.slice(0, 8)}</small></div><button className="p-subtle-button" disabled={busy} onClick={() => { void run(async () => { await personalRequest(`/choices/${comparison.id}`, {}, 'DELETE'); await refresh(); setNotice('Comparison undone. The model was rebuilt from your remaining choices.'); }); }}><Icon name="undo" size={14} />Undo</button></article>)}{!activeComparisons.length && <p className="p-caption">Your comparisons will appear here, with the original choice and your reason.</p>}</div></section>
    <section className="p-data-control"><div><span className="p-eyebrow">PORTABLE. CORRECTABLE. YOURS.</span><h2>Keep control of your record.</h2><p>Export source versions, exposures, choices, predictions, model weights, and training rows. Delete a collection or exploration when it no longer belongs here.</p><a className="vr-button vr-button-primary" href="/api/personal/export" download><Icon name="download" size={15} />Export complete record</a></div><details><summary>Manage saved data</summary><div>{snapshot.datasets.map(dataset => <div key={dataset.id}><span><strong>{dataset.title}</strong><small>Collection · {dataset.itemRefs.length} items</small></span><button onClick={() => setDeleting({ type: 'datasets', id: dataset.id, title: dataset.title })} aria-label={`Delete ${dataset.title}`}><Icon name="trash" size={15} /></button></div>)}{snapshot.recentSessions.map(session => <div key={session.id}><span><strong>{session.query}</strong><small>Exploration · {session.unitCount} cards</small></span><button onClick={() => setDeleting({ type: 'sessions', id: session.id, title: session.query })} aria-label={`Delete ${session.query}`}><Icon name="trash" size={15} /></button></div>)}</div></details></section>
    {editing && <PersonalDialog title={editing === 'new' ? 'Add to your memory' : 'Correct this memory'} onClose={() => setEditing(null)}><form className="p-memory-form" onSubmit={event => void save(event)}><label>Memory type<select value={kind} onChange={event => setKind(event.target.value as PersonalProfileFact['kind'])}><option value="knowledge">Something I know</option><option value="preference">A preference I want to state</option><option value="value">A value or tradeoff</option></select></label><label>What should the engine remember?<textarea rows={4} autoFocus maxLength={1000} value={value} onChange={event => setValue(event.target.value)} placeholder="I know React hooks, or I value practical depth over brevity…" /></label><label>Applies to domain<input maxLength={80} value={domain} onChange={event => setDomain(event.target.value)} list="p-domains" /><datalist id="p-domains"><option value="content" /><option value="design" /><option value="portraits" />{snapshot.models.map(model => <option key={model.id} value={model.domain} />)}</datalist></label><p className="p-caption">A preference in one domain is not assumed to apply everywhere. Stated preferences and learned weights remain distinguishable.</p><button className="vr-button vr-button-primary" disabled={busy || !value.trim() || !domain.trim()}>Save memory<Icon name="check" size={15} /></button></form></PersonalDialog>}
    {deleting && <PersonalDialog title="Delete this saved data?" onClose={() => setDeleting(null)}><div className="p-delete-dialog"><h3>{deleting.title}</h3><p>{deleting.type === 'facts' ? 'This memory will be removed from your profile.' : 'Related personal records and derived learning data will be removed or rebuilt. Shared content used elsewhere may remain.'}</p><div><button className="vr-button vr-button-secondary" onClick={() => setDeleting(null)}>Keep it</button><button className="vr-button vr-button-primary" disabled={busy} onClick={() => { void run(async () => { await personalRequest(`/${deleting.type}/${deleting.id}`, {}, 'DELETE'); await refresh(); setDeleting(null); setNotice('Saved data deleted and affected learning state rebuilt.'); }); }}>Delete</button></div></div></PersonalDialog>}
  </div>;
}
